import { PLATFORM } from "aurelia-pal";

// for webpack, so we don't have to keep repeating PLATFORM.moduleName everywhere..
PLATFORM.moduleName("pages/default-leaf.html");
PLATFORM.moduleName("pages/default-parent.html");
PLATFORM.moduleName("pages/default");
PLATFORM.moduleName("pages/page1");
PLATFORM.moduleName("pages/page1/page1");
PLATFORM.moduleName("pages/page1/page1/page1");
PLATFORM.moduleName("pages/page1/page1/page1/page1");
PLATFORM.moduleName("pages/page1/page1/page1/page2");
PLATFORM.moduleName("pages/page1/page1/page2");
PLATFORM.moduleName("pages/page1/page2");
PLATFORM.moduleName("pages/page1/page2/page1");
PLATFORM.moduleName("pages/page1/page2/page2");
PLATFORM.moduleName("pages/page1/page2/page3");
PLATFORM.moduleName("pages/page1/page3");
PLATFORM.moduleName("pages/page2");
PLATFORM.moduleName("pages/page2/page1");
PLATFORM.moduleName("pages/page2/page2");
PLATFORM.moduleName("pages/page3");
PLATFORM.moduleName("pages/page3/page1");
PLATFORM.moduleName("pages/page3/page2");
PLATFORM.moduleName("pages/page3/page2/page1");
PLATFORM.moduleName("pages/page3/page2/page1/page1");
PLATFORM.moduleName("pages/page3/page2/page1/page2");
PLATFORM.moduleName("pages/page3/page2/page2");
PLATFORM.moduleName("pages/page3/page2/page3");
PLATFORM.moduleName("pages/page3/page3");
PLATFORM.moduleName("pages/page3/page4");
